# Generated by Django 4.2.5 on 2023-09-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=200)),
                ("sub_county", models.CharField(max_length=200)),
                ("home_location", models.CharField(max_length=200)),
                ("sub_location", models.CharField(max_length=200)),
                ("address_no", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="OwnerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("id_number", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("deed_no", models.IntegerField()),
                ("sheet_no", models.BigIntegerField()),
                ("sheet_image", models.ImageField(upload_to="")),
                (
                    "location",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.ownerdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GreenCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16, unique=True)),
                ("expiration_date", models.DateField()),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.landmark",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.ownerdetail",
                    ),
                ),
            ],
        ),
    ]
