# Generated by Django 4.2.5 on 2023-09-25 05:34

from django.db import migrations, models
import landDetails.models


class Migration(migrations.Migration):
    dependencies = [
        ("landDetails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="sheet_image",
            field=models.ImageField(upload_to=landDetails.models.upload_location),
        ),
    ]
