# Generated by Django 4.2.5 on 2023-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landDetails", "0002_alter_landmark_sheet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greencard",
            name="card_number",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="deed_no",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="sheet_no",
            field=models.BigIntegerField(unique=True),
        ),
    ]
