# Generated by Django 4.2.5 on 2023-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "landDetails",
            "0003_alter_greencard_card_number_alter_landmark_deed_no_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="greencard",
            name="card_number",
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
