# Generated by Django 4.2.5 on 2023-10-05 19:41

from django.db import migrations, models
import django.db.models.deletion
import landDetails.models


class Migration(migrations.Migration):
    dependencies = [
        ("landDetails", "0004_alter_greencard_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lease",
                    models.ImageField(
                        null=True, upload_to=landDetails.models.document_upload_location
                    ),
                ),
                (
                    "rent",
                    models.ImageField(
                        null=True, upload_to=landDetails.models.document_upload_location
                    ),
                ),
                (
                    "landmark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.landmark",
                    ),
                ),
            ],
        ),
    ]
