# Generated by Django 4.2.5 on 2023-10-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landDetails", "0005_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ammount", models.IntegerField()),
                (
                    "documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.documents",
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.landmark",
                    ),
                ),
                (
                    "rentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landDetails.ownerdetail",
                    ),
                ),
            ],
        ),
    ]
